name: "insurance_dbt"
version: "1.0.0"
config-version: 2

profile: "insurance_dbt_zna"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  insurance_dbt:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: table
    marts:
      +materialized: table
    python-models:
      +materialized: table
    synthetic:
      +enabled: true
      +materialized: table



seeds:
  insurance_dbt:
    +quote_columns: false

sources:
  +freshness:
    warn_after:
      count: 9999
      period: day
flags:
  require_generic_test_arguments_property: true